add ping command

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -36,9 +36,12 @@ jobs:
     #     npm ci
     #     npm run build
 
+    - name: Debug DNS Resolution
+    run: ping -c 4 ${{ secrets.SERVER_HOST }} || echo "Cannot resolve hostname"
+  
+
     - name: Debug SSH Connection
       run: ssh -o StrictHostKeyChecking=no -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} echo "SSH Connection Successful"
-
 
     # Copy Hasil ke Server
     - name: Deploy to Server
